# Generated by Django 5.1.2 on 2024-11-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="operating_hours",
            field=models.CharField(default="9:00 AM - 9:00 PM", max_length=200),
        ),
    ]
