# Generated by Django 5.1.3 on 2024-11-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_student_name_student_account_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.menu",
            ),
        ),
    ]
