# Generated by Django 5.1.3 on 2024-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_order_options_alter_order_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(related_name="orders", to="core.item"),
        ),
    ]
